project:
  type: website
  output-dir: docs

website:
  title: "Luis Cunha"
  site-url: "https://luisfelipebr.github.io/"
  page-footer: 
    left: "© Luis Cunha, 2022.<br />Made with [Quarto](https://quarto.org/)."
    right: 
      - icon: envelope
        href: mailto:luisfelipebc@outlook.com
      - icon: twitter 
        href: https://twitter.com/lwowis
      - icon: github
        href: https://github.com/luisfelipebr
  navbar:
    background: secondary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - blog.qmd
      - projects.qmd
      - cv.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true
    